config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  validates :title , presence: true, 
                    length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles= Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def edit 
    @article = Article.find(params[:id])
  end
  
  def create 
    @article = Article.new(article_params);
    if @article.save 
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def update
    @article = Article.find(params[:id])
    if( @article.update(article_params))
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
  
  private 
  def article_params
    params.require(:article).permit(:title,:text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for :article do |f| %>

<% if @article.errors.any? %>
  <p>Errors found, details below</p>
  <ul>
    <% @article.errors.full_messages do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <%end %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  
  <%= f.label :text %>
  <%= f.text_area :text %>
  
  <%= f.submit %>
  

<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>
<p> <%= link_to 'My Blog', articles_path %> |
<%= link_to 'New Blog', new_article_path %></p>
<table> 
<th>Title</th>
<th>Text</th>
<th colspan="2"></th>
<% @articles.each do |article| %>
  <tr>
    <td>  <%= article.title %> </td>
    <td><%= article.text %> </td>
    <td> <%= link_to "Show", article_path(article) %> </td>
    <td> <%= link_to "Edit", edit_article_path(article) %> </td>
    <td><%= link_to "Delete" , article_path(article) , method: :delete, data: {confirm: "are you sure"} %></td>
  </tr>
<% end%>

</table>

app/views/articles/new.html.erb
<h1> New Article</h1>

<%= render 'form' %>
<p> <%= link_to "Back", articles_path %></p>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p><%= link_to "Back", articles_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello Rails</h1>